/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.uvsq.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 02-08-2017
 * 
 * XDoclet definition:
 * @struts.form name="homepageForm"
 */
public class HomepageForm extends ActionForm 
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String friendname;
	private String content_post;

	public String getFriendname() 
	{
		return friendname;
	}

	public void setFriendname(String friendname) 
	{
		this.friendname = friendname;
	}
	
	public String getContent_post() 
	{
		return content_post;
	}

	public void setContent_post(String content_post) 
	{
		this.content_post = content_post;
	}
}