/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.domain.Student;
import com.form.LoginForm;
import com.idao.IStudentDAO;

/** 
 * MyEclipse Struts
 * Creation date: 02-06-2017
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" parameter="flag" scope="request"
 */
public class LoginAction extends DispatchAction 
{
	private IStudentDAO iStudentDAO;
	
	/*
	 * Generated Methods
	 */
	public void setiStudentDAO(IStudentDAO iStudentDAO) 
	{
		this.iStudentDAO = iStudentDAO;
	}

	/** 
	 * Method login
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward login(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) 
	{
		LoginForm loginForm = (LoginForm) form;

		Student s_forChecking = new Student();
		s_forChecking.setPwd(loginForm.getPassword());
		Student s_result = null;
		
		if(loginForm.getUsername().indexOf("@") == -1)
		{
			s_forChecking.setTel(loginForm.getUsername());
			s_result = iStudentDAO.checkStuByPhone(s_forChecking);
		}
		else
		{
			s_forChecking.setEmail(loginForm.getUsername());
			s_result = iStudentDAO.checkStuByEmail(s_forChecking);
		}
		
		if(s_result !=null )
		{
			request.getSession().setAttribute("userInfo", s_result);
		}
		else
		{
			System.out.println("non this student");
		}
		
		return null;
	}
}