/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.domain.Student;
import com.form.SignupForm;
import com.idao.IStudentDAO;

/** 
 * MyEclipse Struts
 * Creation date: 02-06-2017
 * 
 * XDoclet definition:
 * @struts.action path="/signup" name="signupForm" parameter="flag" scope="request"
 */
public class SignupAction extends DispatchAction 
{
	private IStudentDAO iStudentDAO;
	/*
	 * Generated Methods
	 */
	public void setiStudentDAO(IStudentDAO iStudentDAO) 
	{
		this.iStudentDAO = iStudentDAO;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward signups1(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) 
	{
		SignupForm signupForm = (SignupForm) form;
		
		Student s = new Student();
		s.setEmail(signupForm.getEmail());
		s.setTel(signupForm.getTel());
		s.setPwd(signupForm.getPassword());
		
		iStudentDAO.add(s);
		request.getSession().setAttribute("stu_id", s.getId());
		
		return mapping.findForward("tosignup2");
	}
	
	public ActionForward signups2(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) 
	{
		SignupForm signupForm = (SignupForm) form;
		int id = (Integer) request.getSession().getAttribute("stu_id");
		
		Student s = iStudentDAO.getStuById(id);
		s.setName(signupForm.getName());
		s.setSex(signupForm.getSex());
		s.setBirthday(signupForm.getBirthday());
		
		iStudentDAO.update(s);
		
		return mapping.findForward("tosignup3");
	}
	
	public ActionForward signups3(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) 
	{
		SignupForm signupForm = (SignupForm) form;
		int id = (Integer) request.getSession().getAttribute("stu_id");
		
		Student s = iStudentDAO.getStuById(id);
		s.setName(signupForm.getName());
		s.setSex(signupForm.getSex());
		s.setBirthday(signupForm.getBirthday());
		
		iStudentDAO.update(s);
		
		return null;
		//return mapping.findForward("tosignup3");
	}
}