/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.uvsq.action;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.uvsq.domain.Post;
import com.uvsq.domain.Student;
import com.uvsq.form.HomepageForm;
import com.uvsq.idao.IFriendshipDAO;
import com.uvsq.idao.IPostDAO;
import com.uvsq.idao.IStudentDAO;

/** 
 * MyEclipse Struts
 * Creation date: 02-08-2017
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class HomepageAction extends DispatchAction 
{
	private IStudentDAO iStudentDAO;
	private IFriendshipDAO iFriendshipDAO;
	private IPostDAO iPostDAO;

	public void setiFriendshipDAO(IFriendshipDAO iFriendshipDAO) 
	{
		this.iFriendshipDAO = iFriendshipDAO;
	}

	public void setiStudentDAO(IStudentDAO iStudentDAO) 
	{
		this.iStudentDAO = iStudentDAO;
	}
	
	public void setiPostDAO(IPostDAO iPostDAO)
	{
		this.iPostDAO = iPostDAO;
	}

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward tohomepage(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) 
	{	
		Student s = (Student) request.getSession().getAttribute("userInfo");
		Student s_result = iStudentDAO.getStuById(s.getId());
		
		List<Post> showPosts = new ArrayList<Post>();
		
		List<Post> monPosts = iPostDAO.showPostList(s_result);
		if(monPosts != null)
		{
			showPosts.addAll(monPosts);
		}
		
		List<Student> friends = iFriendshipDAO.showFriendList(s_result);
		
		if(friends != null)
		{
			for(Student stu : friends)
			{
				List<Post> posts = iPostDAO.showPostList(stu);
				
				if(posts != null)
				{
					showPosts.addAll(posts);
				}
			}
		}
		
		Collections.sort(showPosts);
		
		request.getSession().setAttribute("userInfo", s_result);
		request.getSession().setAttribute("showPosts", showPosts);
		
		return mapping.findForward("tohomepage");
	}
	
	public ActionForward tosearchFriend(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) 
	{	
		request.getSession().setAttribute("friendInfo", null);
		return mapping.findForward("searchFriend");
	}
	
	public ActionForward searchFriend(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) 
	{
		HomepageForm homepageForm = (HomepageForm) form;
		request.getSession().setAttribute("friendInfo", null);
		
		List<Student> lists = iStudentDAO.getStuByName(homepageForm.getFriendname());
		
		if(lists != null)
		{
			request.getSession().setAttribute("friendInfo", lists);
		}
		
		return mapping.findForward("searchFriend");
	}
	
	public ActionForward addFriend(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) 
	{	
		String friendId = request.getParameter("friendId");
		
		Student s1 = (Student) request.getSession().getAttribute("userInfo");
		Student s2 = iStudentDAO.getStuById(Integer.parseInt(friendId));
		
		if(!iFriendshipDAO.isFriend(s1, s2))
		{
			iFriendshipDAO.makeFriend(s1, s2);
		}
		
		return mapping.findForward("tohomepage");
	}
	
	public ActionForward Myprofile(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) 
	{
		Student s = (Student) request.getSession().getAttribute("userInfo");
		s = iStudentDAO.getStuById(s.getId());
		
		request.getSession().setAttribute("userProfile", s);
		request.getSession().setAttribute("showAdd", false);
		return mapping.findForward("toprofile");
	}
	
	public ActionForward Friendprofile(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) 
	{
		Student s1 = (Student) request.getSession().getAttribute("userInfo");
		
		String friendId = request.getParameter("friendId");
		Student s2 = iStudentDAO.getStuById(Integer.parseInt(friendId));
		
		if(iFriendshipDAO.isFriend(s1, s2))
		{
			request.getSession().setAttribute("showAdd", false);
		}
		else
		{
			request.getSession().setAttribute("showAdd", true);
		}
		
		request.getSession().setAttribute("userProfile", s2);
		return mapping.findForward("toprofile");
	}
	
	public ActionForward friendList(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) 
	{
		Student s = (Student) request.getSession().getAttribute("userInfo");
		Student s_result = iStudentDAO.getStuById(s.getId());
		
		List<Student> friendList = iFriendshipDAO.showFriendList(s_result);
		
		if(friendList != null)
		{
			request.getSession().setAttribute("friendList", friendList);
		}
		else
		{
			request.getSession().setAttribute("friendList", null);
		}
		
		return mapping.findForward("tofriendlist");
	}
	
	public ActionForward post(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) 
	{	
		HomepageForm homepageForm = (HomepageForm) form;
		
		Student s = (Student) request.getSession().getAttribute("userInfo");
		
		Post p = new Post();
		p.setContent(homepageForm.getContent_post());
		p.setNumLike(0);
		p.setNumHate(0);
		p.setStudent(s);
		
		iPostDAO.add(p);
		
		Student s_result = iStudentDAO.getStuById(s.getId());
		
		List<Post> showPosts = new ArrayList<Post>();
		
		List<Post> monPosts = iPostDAO.showPostList(s_result);
		if(monPosts != null)
		{
			showPosts.addAll(monPosts);
		}
		
		List<Student> friends = iFriendshipDAO.showFriendList(s_result);
		
		if(friends != null)
		{
			for(Student stu : friends)
			{
				List<Post> posts = iPostDAO.showPostList(stu);
				
				if(posts != null)
				{
					showPosts.addAll(posts);
				}
			}
		}
		
		Collections.sort(showPosts);
		
		request.getSession().setAttribute("userInfo", s_result);
		request.getSession().setAttribute("showPosts", showPosts);
		
		return mapping.findForward("tohomepage");
	}
	
	public ActionForward like(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) 
	{
		String postId = request.getParameter("postId");
		
		Post p = (Post) iPostDAO.findById(Post.class, Integer.parseInt(postId));
		p.setNumLike(p.getNumLike() + 1);
		iPostDAO.update(p);
		
		Student s = (Student) request.getSession().getAttribute("userInfo");
		Student s_result = iStudentDAO.getStuById(s.getId());
		
		List<Post> showPosts = new ArrayList<Post>();
		
		List<Post> monPosts = iPostDAO.showPostList(s_result);
		if(monPosts != null)
		{
			showPosts.addAll(monPosts);
		}
		
		List<Student> friends = iFriendshipDAO.showFriendList(s_result);
		
		if(friends != null)
		{
			for(Student stu : friends)
			{
				List<Post> posts = iPostDAO.showPostList(stu);
				
				if(posts != null)
				{
					showPosts.addAll(posts);
				}
			}
		}
		
		Collections.sort(showPosts);
		
		request.getSession().setAttribute("userInfo", s_result);
		request.getSession().setAttribute("showPosts", showPosts);
		
		return mapping.findForward("tohomepage");
	}
	
	public ActionForward hate(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) 
	{
		String postId = request.getParameter("postId");
		
		Post p = (Post) iPostDAO.findById(Post.class, Integer.parseInt(postId));
		p.setNumHate(p.getNumHate() + 1);
		iPostDAO.update(p);
		
		Student s = (Student) request.getSession().getAttribute("userInfo");
		Student s_result = iStudentDAO.getStuById(s.getId());
		
		List<Post> showPosts = new ArrayList<Post>();
		
		List<Post> monPosts = iPostDAO.showPostList(s_result);
		if(monPosts != null)
		{
			showPosts.addAll(monPosts);
		}
		
		List<Student> friends = iFriendshipDAO.showFriendList(s_result);
		
		if(friends != null)
		{
			for(Student stu : friends)
			{
				List<Post> posts = iPostDAO.showPostList(stu);
				
				if(posts != null)
				{
					showPosts.addAll(posts);
				}
			}
		}
		
		Collections.sort(showPosts);
		
		request.getSession().setAttribute("userInfo", s_result);
		request.getSession().setAttribute("showPosts", showPosts);
		
		return mapping.findForward("tohomepage");
	}
}